const mongoose = require('mongoose');
const Medicine = require('./models/Medicine');
const dotenv = require('dotenv');

dotenv.config();

const medicines = [
  { name: "ACNETRET-10 Capsule", category: "Capsule", dosage: "10mg", form: "Capsule" },
  { name: "ACNETRET-20 Capsule", category: "Capsule", dosage: "20mg", form: "Capsule" },
  { name: "ADACLIN Gel", category: "Gel", dosage: "NA", form: "Gel" },
  { name: "ADAZOYL", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "ALENTIN Chewable Tablet", category: "Chewable Tablet", dosage: "NA", form: "Chewable Tablet" },
  { name: "ALENTIN Suspension", category: "Suspension", dosage: "NA", form: "Suspension" },
  { name: "ALERNIL 120 Tablet", category: "Tablet", dosage: "120mg", form: "Tablet" },
  { name: "ALERNIL 180 Tablet", category: "Tablet", dosage: "180mg", form: "Tablet" },
  { name: "ALERNIL Suspension", category: "Suspension", dosage: "NA", form: "Suspension" },
  { name: "ALERSEF Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "ALERSEF Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "ALFAPRO - 0.4 Capsule", category: "Capsule", dosage: "0.4mg", form: "Capsule" },
  { name: "AMCAB-10 Tablet", category: "Tablet", dosage: "10mg", form: "Tablet" },
  { name: "AMCAB-2.5 Tablet", category: "Tablet", dosage: "2.5mg", form: "Tablet" },
  { name: "AMCAB-5 Tablet", category: "Tablet", dosage: "5mg", form: "Tablet" },
  { name: "AMCAB-AT Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "AMIGUT", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "AMLOTAN-27.5 Tablet", category: "Tablet", dosage: "27.5mg", form: "Tablet" },
  { name: "AMLOTAN-30 Tablet", category: "Tablet", dosage: "30mg", form: "Tablet" },
  { name: "AMLOTAN-55 Tablet", category: "Tablet", dosage: "55mg", form: "Tablet" },
  { name: "APET Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "APET Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "ATOLIMUS 0.03% Ointment", category: "Ointment", dosage: "0.03%", form: "Ointment" },
  { name: "ATOLIMUS 0.1% Ointment", category: "Ointment", dosage: "0.1%", form: "Ointment" },
  { name: "BENZADINE Mouthwash", category: "Mouthwash", dosage: "NA", form: "Mouthwash" },
  { name: "BETA-2 Expectorant Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "BETA-2 Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "BETA-BM", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "BETA-BM Paediatric Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "BETA-S Ointment", category: "Ointment", dosage: "NA", form: "Ointment" },
  { name: "BETACREAM Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "BETACREAM-C Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "BETACREAM-N Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "BRIVERA 100", category: "Capsule", dosage: "100mg", form: "Capsule" },
  { name: "BRIVERA 50", category: "Capsule", dosage: "50mg", form: "Capsule" },
  { name: "CALVIT CCM Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "CALVIT CT Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "CALVIT Suspension", category: "Suspension", dosage: "NA", form: "Suspension" },
  { name: "CALVIT Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "CARBOTRAP", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "CARBOTRAP 25 Tablet", category: "Tablet", dosage: "25mg", form: "Tablet" },
  { name: "CAREAGE Capsule", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "CECLO 100 Tablet", category: "Tablet", dosage: "100mg", form: "Tablet" },
  { name: "CECLO 200 XR Tablet", category: "Tablet", dosage: "200mg", form: "Tablet" },
  { name: "CECLO Gel 30 g", category: "Gel", dosage: "30g", form: "Gel" },
  { name: "CHYMOSIN FORTE Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "CHYMOSIN Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "CLAREX 500 Tablet", category: "Tablet", dosage: "500mg", form: "Tablet" },
  { name: "CLINCIN Gel", category: "Gel", dosage: "NA", form: "Gel" },
  { name: "CLOMIGEN", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "CLOMIGEN PLUS Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "CLOMIRET Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "COLDIN Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "COLDIN Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "COLDIN-P Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "COLOMINE-400 Tablet", category: "Tablet", dosage: "400mg", form: "Tablet" },
  { name: "COLOMINE-800 Tablet", category: "Tablet", dosage: "800mg", form: "Tablet" },
  { name: "CONAZ Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "CONAZ Lotion", category: "Lotion", dosage: "NA", form: "Lotion" },
  { name: "CONAZ Solution", category: "Solution", dosage: "NA", form: "Solution" },
  { name: "COQTEN-100 Capsule", category: "Capsule", dosage: "100mg", form: "Capsule" },
  { name: "COQTEN-60 Capsule", category: "Capsule", dosage: "60mg", form: "Capsule" },
  { name: "CORTY Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "COXIPRO", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "COXIPRO 90 Tablet", category: "Tablet", dosage: "90mg", form: "Tablet" },
  { name: "CRALFATE", category: "Other", dosage: "NA", form: "Sachet" },
  { name: "DAPAZ 10", category: "Capsule", dosage: "10mg", form: "Capsule" },
  { name: "DAPAZ 5", category: "Capsule", dosage: "5mg", form: "Capsule" },
  { name: "DECOPAN 10 Tablet", category: "Tablet", dosage: "10mg", form: "Tablet" },
  { name: "DECOPAN 20 Tablet", category: "Tablet", dosage: "20mg", form: "Tablet" },
  { name: "DERMIPREV Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "DIGESTAL Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "DIGICON Capsule", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "DIGICON 200 Capsule", category: "Capsule", dosage: "200mg", form: "Capsule" },
  { name: "DIGIROLFIN 5%", category: "Cream", dosage: "5%", form: "Cream" },
  { name: "DIGISEP 10 Tablet", category: "Tablet", dosage: "10mg", form: "Tablet" },
  { name: "DIGISEP 5 Tablet", category: "Tablet", dosage: "5mg", form: "Tablet" },
  { name: "DIPLAR-10 Tablet", category: "Tablet", dosage: "10mg", form: "Tablet" },
  { name: "DIPLAR-20 Tablet", category: "Tablet", dosage: "20mg", form: "Tablet" },
  { name: "DIPLAR-40 Tablet", category: "Tablet", dosage: "40mg", form: "Tablet" },
  { name: "DJ-CITRAl K Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "DJ-CITRAL Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "EFFIMET-1000 XR Tablet", category: "Tablet", dosage: "1000mg", form: "Tablet" },
  { name: "EFFIMET-500 Tablet", category: "Tablet", dosage: "500mg", form: "Tablet" },
  { name: "EFFIMET-500 XR Tablet", category: "Tablet", dosage: "500mg", form: "Tablet" },
  { name: "EFFIMET-850 Tablet", category: "Tablet", dosage: "850mg", form: "Tablet" },
  { name: "ENIL-10 Tablet", category: "Tablet", dosage: "10mg", form: "Tablet" },
  { name: "ENIL-2.5 Tablet", category: "Tablet", dosage: "2.5mg", form: "Tablet" },
  { name: "ENIL-5 Tablet", category: "Tablet", dosage: "5mg", form: "Tablet" },
  { name: "EPICOS 100", category: "Capsule", dosage: "100mg", form: "Capsule" },
  { name: "EPICOS 50", category: "Capsule", dosage: "50mg", form: "Capsule" },
  { name: "ESONORM 20 Tablet", category: "Tablet", dosage: "20mg", form: "Tablet" },
  { name: "ESONORM 40", category: "Tablet", dosage: "40mg", form: "Tablet" },
  { name: "FEBU 40 Tablet", category: "Tablet", dosage: "40mg", form: "Tablet" },
  { name: "FEBU 80 Tablet", category: "Tablet", dosage: "80mg", form: "Tablet" },
  { name: "FEROFOLIC Capsule", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "FEROFOLIC Drops", category: "Drops", dosage: "NA", form: "Drops" },
  { name: "FEROFOLIC Plus Capsule", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "FEROFOLIC Plus Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "FEROFOLIC Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "FEROFOZIN Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "FIBRINIC 250 Tablet", category: "Tablet", dosage: "250mg", form: "Tablet" },
  { name: "FIBRINIC 500 Tablet", category: "Tablet", dosage: "500mg", form: "Tablet" },
  { name: "FLONTIN 250 Tablet", category: "Tablet", dosage: "250mg", form: "Tablet" },
  { name: "FLONTIN 500 Tablet", category: "Tablet", dosage: "500mg", form: "Tablet" },
  { name: "FLONTIN 750 Tablet", category: "Tablet", dosage: "750mg", form: "Tablet" },
  { name: "FLUTIPRO Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "FOLTAB Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "FORTIPLEX Capsule", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "FORTIPLEX SYRUP", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "FORTIPLEX-M Capsule", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "FORTIPLEX-M Drops", category: "Drops", dosage: "NA", form: "Drops" },
  { name: "FORTIPLEX-Z SYRUP", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "GLUNITA 5", category: "Tablet", dosage: "5mg", form: "Tablet" },
  { name: "GRELOR", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "GRELOR 90 Tablet", category: "Tablet", dosage: "90mg", form: "Tablet" },
  { name: "HEPAPROT 500 Tablet", category: "Tablet", dosage: "500mg", form: "Tablet" },
  { name: "HEPAPROT Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "HYPOLIP-10 Tablet", category: "Tablet", dosage: "10mg", form: "Tablet" },
  { name: "HYPOLIP-20 Tablet", category: "Tablet", dosage: "20mg", form: "Tablet" },
  { name: "HYPOLIP-5 Tablet", category: "Tablet", dosage: "5mg", form: "Tablet" },
  { name: "HYQUIN 200 Tablet", category: "Tablet", dosage: "200mg", form: "Tablet" },
  { name: "HYQUIN 400 Tablet", category: "Tablet", dosage: "400mg", form: "Tablet" },
  { name: "ITORIDE 50", category: "Tablet", dosage: "50mg", form: "Tablet" },
  { name: "KELYTIC-20% Ointment", category: "Ointment", dosage: "20%", form: "Ointment" },
  { name: "KELYTIC-40% Ointment", category: "Ointment", dosage: "40%", form: "Ointment" },
  { name: "L-RET Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "LEFLONTIN 250 Tablet", category: "Tablet", dosage: "250mg", form: "Tablet" },
  { name: "LEFLONTIN 500 Tablet", category: "Tablet", dosage: "500mg", form: "Tablet" },
  { name: "LEFLONTIN 750 Tablet", category: "Tablet", dosage: "750mg", form: "Tablet" },
  { name: "LIVOLAX Solution", category: "Solution", dosage: "NA", form: "Solution" },
  { name: "LOTAN-25 Tablet", category: "Tablet", dosage: "25mg", form: "Tablet" },
  { name: "LOTAN-50 Tablet", category: "Tablet", dosage: "50mg", form: "Tablet" },
  { name: "LOTAN-H", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "LUTRET Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "LYSOVIT Drops", category: "Drops", dosage: "NA", form: "Drops" },
  { name: "LYSOVIT Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "MECOVIT 1500 Sublingual Tablet", category: "Tablet", dosage: "1500mg", form: "Tablet" },
  { name: "METAQUIN", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "METHRIN Lotion", category: "Lotion", dosage: "NA", form: "Lotion" },
  { name: "METOP-12.5 Tablet", category: "Tablet", dosage: "12.5mg", form: "Tablet" },
  { name: "METOP-25 Tablet", category: "Tablet", dosage: "25mg", form: "Tablet" },
  { name: "METOP-25 XR Tablet", category: "Tablet", dosage: "25mg", form: "Tablet" },
  { name: "METOP-50 Tablet", category: "Tablet", dosage: "50mg", form: "Tablet" },
  { name: "METOP-50 XR Tablet", category: "Tablet", dosage: "50mg", form: "Tablet" },
  { name: "MICONA Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "MONKAST 10 Tablet", category: "Tablet", dosage: "10mg", form: "Tablet" },
  { name: "MONKAST 4 Chewable Tablet", category: "Chewable Tablet", dosage: "4mg", form: "Chewable Tablet" },
  { name: "MONKAST 5 Chewable Tablet", category: "Chewable Tablet", dosage: "5mg", form: "Chewable Tablet" },
  { name: "MONKAST LC Suspension", category: "Suspension", dosage: "NA", form: "Suspension" },
  { name: "MONKAST LC Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "MUROC Ointment", category: "Ointment", dosage: "NA", form: "Ointment" },
  { name: "NAPROBEST 250 Tablet", category: "Tablet", dosage: "250mg", form: "Tablet" },
  { name: "NAPROBEST 500 Tablet", category: "Tablet", dosage: "500mg", form: "Tablet" },
  { name: "NEPOFEN-50 Tablet", category: "Tablet", dosage: "50mg", form: "Tablet" },
  { name: "NEPOFEN Mouthwash", category: "Mouthwash", dosage: "NA", form: "Mouthwash" },
  { name: "NEPOFEN Plus Gel", category: "Gel", dosage: "NA", form: "Gel" },
  { name: "NEPOFEN-K Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "NEPOFEN-SR Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "NERVILIN-50 Capsule", category: "Capsule", dosage: "50mg", form: "Capsule" },
  { name: "NERVILIN-75 Capsule", category: "Capsule", dosage: "75mg", form: "Capsule" },
  { name: "NERVILIN-M Capsule", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "NERVIT Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "NORMOGEL MPS Suspension", category: "Suspension", dosage: "NA", form: "Suspension" },
  { name: "NORMOGEL OS Suspension", category: "Suspension", dosage: "NA", form: "Suspension" },
  { name: "NORMOGEL Suspension", category: "Suspension", dosage: "NA", form: "Suspension" },
  { name: "OFLONTIN 200 Tablet", category: "Tablet", dosage: "200mg", form: "Tablet" },
  { name: "OFLONTIN 400 Tablet", category: "Tablet", dosage: "400mg", form: "Tablet" },
  { name: "OFLONTIN 50 Suspension", category: "Suspension", dosage: "50mg", form: "Suspension" },
  { name: "OFLONTIN DT 100", category: "Tablet", dosage: "100mg", form: "Tablet" },
  { name: "OFLONTIN DT 50", category: "Tablet", dosage: "50mg", form: "Tablet" },
  { name: "ONDATRON 4 Tablet", category: "Tablet", dosage: "4mg", form: "Tablet" },
  { name: "ONDATRON 8 Tablet", category: "Tablet", dosage: "8mg", form: "Tablet" },
  { name: "ONDATRON SYRUP", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "OPIDOL Capsule", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "OPIDOL P Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "OROCHLOR Oral Rinse", category: "Mouthwash", dosage: "NA", form: "Mouthwash" },
  { name: "OROLONE Paste", category: "Paste", dosage: "NA", form: "Paste" },
  { name: "PANORMA 40 Tablet", category: "Tablet", dosage: "40mg", form: "Tablet" },
  { name: "PANORMA-D", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "PARACAF Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "PASMODIN DROPS", category: "Drops", dosage: "NA", form: "Drops" },
  { name: "PASMODIN Suspension", category: "Suspension", dosage: "NA", form: "Suspension" },
  { name: "PERI-AC Capsule", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "PERICEF 100 DT", category: "Tablet", dosage: "100mg", form: "Tablet" },
  { name: "PERICEF 200 Tablet", category: "Tablet", dosage: "200mg", form: "Tablet" },
  { name: "PERICEF 50 Dry Syrup", category: "Dry Syrup", dosage: "50mg", form: "Dry Syrup" },
  { name: "PERICLOX Capsule", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "PERICLOX Dry Syrup", category: "Dry Syrup", dosage: "NA", form: "Dry Syrup" },
  { name: "PERIDOX Capsule", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "PERIFLOX 250 Capsule", category: "Capsule", dosage: "250mg", form: "Capsule" },
  { name: "PERIFLOX 500 Capsule", category: "Capsule", dosage: "500mg", form: "Capsule" },
  { name: "PERIFLOX Dry Syrup", category: "Dry Syrup", dosage: "NA", form: "Dry Syrup" },
  { name: "PERILACT 250 Capsule", category: "Capsule", dosage: "250mg", form: "Capsule" },
  { name: "PERILACT 500 Capsule", category: "Capsule", dosage: "500mg", form: "Capsule" },
  { name: "PERIMOX 250 Capsule", category: "Capsule", dosage: "250mg", form: "Capsule" },
  { name: "PERIMOX 500 Capsule", category: "Capsule", dosage: "500mg", form: "Capsule" },
  { name: "PERIMOX Dry Syrup", category: "Dry Syrup", dosage: "NA", form: "Dry Syrup" },
  { name: "PERIMOX Paediatric Drops", category: "Drops", dosage: "NA", form: "Drops" },
  { name: "POLYCEF 250 Tablet", category: "Tablet", dosage: "250mg", form: "Tablet" },
  { name: "POLYCEF 500 Tablet", category: "Tablet", dosage: "500mg", form: "Tablet" },
  { name: "PROSUN 10 Tablet", category: "Tablet", dosage: "10mg", form: "Tablet" },
  { name: "PROSUN 20 Tablet", category: "Tablet", dosage: "20mg", form: "Tablet" },
  { name: "PROTOGYL DF Suspension", category: "Suspension", dosage: "NA", form: "Suspension" },
  { name: "PROTOGYL DF Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "PROTOGYL FORTE Suspension", category: "Suspension", dosage: "NA", form: "Suspension" },
  { name: "PROTOGYL FORTE Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "PROTOGYL Suspension", category: "Suspension", dosage: "NA", form: "Suspension" },
  { name: "RABENORM Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "RAMIP-2.5 Tablet", category: "Tablet", dosage: "2.5mg", form: "Tablet" },
  { name: "RAMIP-5 Tablet", category: "Tablet", dosage: "5mg", form: "Tablet" },
  { name: "RE-PHOS Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "RETIDERM 0.025% Gel", category: "Gel", dosage: "0.025%", form: "Gel" },
  { name: "RETIDERM 0.05% Gel", category: "Gel", dosage: "0.05%", form: "Gel" },
  { name: "ReVom Drops", category: "Drops", dosage: "NA", form: "Drops" },
  { name: "ReVom Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "RIFAXIM 200", category: "Capsule", dosage: "200mg", form: "Capsule" },
  { name: "RIFAXIM 550", category: "Capsule", dosage: "550mg", form: "Capsule" },
  { name: "ROSULIP-10 Tablet", category: "Tablet", dosage: "10mg", form: "Tablet" },
  { name: "ROSULIP-20 Tablet", category: "Tablet", dosage: "20mg", form: "Tablet" },
  { name: "ROSULIP-5 Tablet", category: "Tablet", dosage: "5mg", form: "Tablet" },
  { name: "SALZIN Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "SECZYL DS Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "SENAZ", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "SENOBIT 20", category: "Tablet", dosage: "20mg", form: "Tablet" },
  { name: "SENOBIT 30", category: "Tablet", dosage: "30mg", form: "Tablet" },
  { name: "SENOBIT 60", category: "Tablet", dosage: "60mg", form: "Tablet" },
  { name: "SEPTIDINE Gargle", category: "Mouthwash", dosage: "NA", form: "Mouthwash" },
  { name: "SEPTIDINE Ointment", category: "Ointment", dosage: "NA", form: "Ointment" },
  { name: "SEPTIDINE Solution 10%", category: "Solution", dosage: "10%", form: "Solution" },
  { name: "SEPTIDINE Solution 5%", category: "Solution", dosage: "5%", form: "Solution" },
  { name: "SITAGLIP-100 Tablet", category: "Tablet", dosage: "100mg", form: "Tablet" },
  { name: "SITAGLIP-50 Tablet", category: "Tablet", dosage: "50mg", form: "Tablet" },
  { name: "SITAGLIP-M 1050 Tablet", category: "Tablet", dosage: "1050mg", form: "Tablet" },
  { name: "SITAGLIP-M 550 Tablet", category: "Tablet", dosage: "550mg", form: "Tablet" },
  { name: "SITAGLIP-M 900 Tablet", category: "Tablet", dosage: "900mg", form: "Tablet" },
  { name: "SLIMAGE Capsule", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "SOLBE-S Ointment", category: "Ointment", dosage: "NA", form: "Ointment" },
  { name: "SOLBET Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "SOLBET-GM Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "SPANBEC-1 Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "SPANBEC-2 Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "SPANBEC-3 Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "SPANBEC-M1 ForteTablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "SPANBEC-M1 Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "SPANBEC-M2 Forte Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "SPANBEC-M2 Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "TAENICID Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "TAFINE Cream", category: "Cream", dosage: "NA", form: "Cream" },
  { name: "TELTAN-20 Tablet", category: "Tablet", dosage: "20mg", form: "Tablet" },
  { name: "TELTAN-40 Tablet", category: "Tablet", dosage: "40mg", form: "Tablet" },
  { name: "TELTAN-80 Tablet", category: "Tablet", dosage: "80mg", form: "Tablet" },
  { name: "THIAVIT Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "THROMBIPREV 2.5", category: "Tablet", dosage: "2.5mg", form: "Tablet" },
  { name: "THROMBIPREV 5", category: "Tablet", dosage: "5mg", form: "Tablet" },
  { name: "TOPCERIN-50", category: "Capsule", dosage: "50mg", form: "Capsule" },
  { name: "TRICEF 100 Dry Syrup", category: "Dry Syrup", dosage: "100mg", form: "Dry Syrup" },
  { name: "TRICEF 100 DT", category: "Tablet", dosage: "100mg", form: "Tablet" },
  { name: "TRICEF 200 Tablet", category: "Tablet", dosage: "200mg", form: "Tablet" },
  { name: "TRICEF 400 Tablet", category: "Tablet", dosage: "400mg", form: "Tablet" },
  { name: "TRICEF Dry Syrup", category: "Dry Syrup", dosage: "NA", form: "Dry Syrup" },
  { name: "TRIOL Ointment", category: "Ointment", dosage: "NA", form: "Ointment" },
  { name: "UDCOL-150 Tablet", category: "Tablet", dosage: "150mg", form: "Tablet" },
  { name: "UDCOL-300 Tablet", category: "Tablet", dosage: "300mg", form: "Tablet" },
  { name: "ULTRASOL Ointment", category: "Ointment", dosage: "NA", form: "Ointment" },
  { name: "ULTRASOL SA Ointment", category: "Ointment", dosage: "NA", form: "Ointment" },
  { name: "VASODRYL Dx", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "VASODRYL Expectorant Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "VASODRYL Paediatric Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "VASODRYL Plus Syrup", category: "Syrup", dosage: "NA", form: "Syrup" },
  { name: "Vit D 800 Drops", category: "Drops", dosage: "800IU", form: "Drops" },
  { name: "VIT-D 60K Chewable Tablet", category: "Chewable Tablet", dosage: "60000IU", form: "Chewable Tablet" },
  { name: "XENECON Capsule", category: "Capsule", dosage: "NA", form: "Capsule" },
  { name: "XILCEF 250 Dry Syrup", category: "Dry Syrup", dosage: "250mg", form: "Dry Syrup" },
  { name: "XILCEF 250 DT", category: "Tablet", dosage: "250mg", form: "Tablet" },
  { name: "XILCEF 500", category: "Tablet", dosage: "500mg", form: "Tablet" },
  { name: "XILCEF 500 Capsule", category: "Capsule", dosage: "500mg", form: "Capsule" },
  { name: "ZINC-DT 10", category: "Tablet", dosage: "10mg", form: "Tablet" },
  { name: "ZINC-DT 20", category: "Tablet", dosage: "20mg", form: "Tablet" },
  { name: "ZOLAMIDE Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "ZOXAFEN Forte Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "ZOXAFEN Tablet", category: "Tablet", dosage: "NA", form: "Tablet" },
  { name: "ZULID 100 Suspension", category: "Suspension", dosage: "100mg", form: "Suspension" },
  { name: "ZULID 200 Suspension", category: "Suspension", dosage: "200mg", form: "Suspension" },
  { name: "ZULID 250 Tablet", category: "Tablet", dosage: "250mg", form: "Tablet" },
  { name: "ZULID 500 Tablet", category: "Tablet", dosage: "500mg", form: "Tablet" }
];

const seedMedicines = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/lincoln_hospital');
    console.log('MongoDB Connected');
    console.log('Starting medicine seed...\n');

    let inserted = 0;
    let skipped = 0;

    for (const med of medicines) {
      try {
        const existing = await Medicine.findOne({ name: med.name });
        if (existing) {
          skipped++;
          continue;
        }
        const medicine = new Medicine({
          ...med,
          manufacturer: 'Various',
          requiresPrescription: true,
          isActive: true
        });
        await medicine.save();
        inserted++;
      } catch (err) {
        console.log(`Skipping ${med.name}: ${err.message}`);
        skipped++;
      }
    }

    const totalMedicines = await Medicine.countDocuments();
    console.log('\n=== MEDICINE SEED COMPLETE ===');
    console.log(`Inserted: ${inserted}`);
    console.log(`Skipped: ${skipped}`);
    console.log(`Total Medicines in Database: ${totalMedicines}`);

    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
};

seedMedicines();
